version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install Gradle
          command: |
            curl -s https://get.sdkman.io | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle
      - run:
          name: Build and test with Gradle
          command: |
            ./gradlew build
            ./gradlew test

