version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build with Maven
          command: mvn clean install
      - run:
          name: Run tests
          command: mvn test

